unique_ids:
  assets:
    standard-page.html: SCLHGTQGX2BNEK2T6QKRQ2NFBSBMIFFJ
    theme.css: DYXAYOY7SLUC3ZEDP73CEJ6QI2BCZCCU
  forms:
    MasterStyleList: Q3NAPEDBJU5O2UYGRTRHWDIEJQC4WCRR
  modules: {}
  scripts: {}
  server_modules: {}
