unique_ids:
  assets:
    standard-page.html: SCLHGTQGX2BNEK2T6QKRQ2NFBSBMIFFJ
    theme.css: DYXAYOY7SLUC3ZEDP73CEJ6QI2BCZCCU
  forms:
    MasterStyleList: '1762243424034510043307832.1397'
  modules: {}
  scripts: {}
  server_modules: {}
